apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor   # <-- Add this line
spec:
  hostPID: true
  hostNetwork: true
  containers:
    - name: cadvisor
      image: gcr.io/google-containers/cadvisor:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: run
          readOnly: false
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
        type: Directory
    - name: run
      hostPath:
        path: /var/run
        type: Directory
    - name: sys
      hostPath:
        path: /sys
        type: Directory
    - name: docker
      hostPath:
        path: /var/lib/docker
        type: Directory
