apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-frontend-service
  namespace: monitoring
spec:
  selector:
    app: fullstack-app-frontend
  ports:
    - protocol: TCP
      port: 80         # port you will access externally
      targetPort: 80   # port in the container
  type: NodePort       # allows external access
