apiVersion: v1
kind: Service
metadata:
  name: student-course-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: student-course-app   # updated to match pod label
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
