apiVersion: v1
kind: Service
metadata:
  name: student-course-app
spec:
  type: NodePort
  selector:
    app: student-course-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
