apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-frontend
spec:
  type: NodePort
  selector:
    app: fullstack-app-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
